### PR TITLE
Ebay price list

### PR DESCRIPTION
**Pull request by Pio-js**

### CODE REVIEW

**Review by EmmanuelOloke — DISMISSED** [review]
Nice work man!

**Review by EmmanuelOloke — COMMENTED** [review]
There seem to be some breaking changes, the app crashes when I search, and I get a 404 page when I try to go to a book page

**Comment by Pio-js** [comment]
> There seem to be some breaking changes, the app crashes when I search, and I get a 404 page when I try to go to a book page

I do not know what it could be, but in my local it is working fine.
Maybe there is some conflict with some changes you are working on.

**Review by frugalcodes — APPROVED** [review]

**Review by EmmanuelOloke — APPROVED** [review]
Nice fix man... Everything works as it should now. Great work

**Pull request merged**
