### PR TITLE
Users and favorites api

### PR DESCRIPTION
**Pull request by ceifeirocv**
add user api, to save user in database for back, only clerkid and email
add favorites api, routes to save, delete, and get favorites and get favorite by id

### CODE REVIEW

**Review by Pio-js — DISMISSED** [review]
Great job

**Review by EmmanuelOloke — DISMISSED** [review]
Really great work Jair... Everything looks good to me

**Review by EmmanuelOloke — DISMISSED** [review]
Nice fix

**Review by EmmanuelOloke — DISMISSED** [review]

**Review by EmmanuelOloke — APPROVED** [review]
Merge conflict resolved. Good to go

**Review by Pio-js — APPROVED** [review]

**Pull request merged**
